/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Paciente;
import java.util.Date;
import utilidades.Encriptado;
import static vistas.Login.dniPaciente;
import static vistas.MenuPrincipal.hoy;

/**
 *
 * @author josavi
 */
public class NuevoPaciente extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaMedica
     */
    public NuevoPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //campoDni.setText(dniPaciente);
        campoDni.setText(dniPaciente);
        Conexion.Conectar();
        Conexion.cargaComboCP(comboCodigoPostal);
        Conexion.desconectar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupTabaquismo = new javax.swing.ButtonGroup();
        buttonGroupAlcohol = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botonRegistrar = new javax.swing.JButton();
        panelCampos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoDni = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        dateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        campoTelefono = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        comboCodigoPostal = new javax.swing.JComboBox<>();
        radioMujer = new javax.swing.JRadioButton();
        radioHombre = new javax.swing.JRadioButton();
        radioOtros = new javax.swing.JRadioButton();
        radioNulo = new javax.swing.JRadioButton();
        radioOcasional = new javax.swing.JRadioButton();
        radioHabitual = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        radioSi = new javax.swing.JRadioButton();
        panelAreas = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoAntecedente = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoPersonalAlerg = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        panelCampos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));
        panelCampos.setOpaque(false);

        jLabel3.setText("NOMBRE");

        jLabel4.setText("DNI");

        jLabel5.setText("APELLIDOS");

        jLabel6.setText("FECHA DE NACIMIENTO");

        jLabel7.setText("TELÉFONO");

        jLabel8.setText("EMAIL");

        jLabel9.setText("CÓDIGO POSTAL");

        jLabel10.setText("SEXO");

        jLabel11.setText("TABAQUISMO");

        jLabel12.setText("CONSUMO DE ALCOHOL");

        campoDni.setEnabled(false);
        campoDni.setName("DNI"); // NOI18N

        campoNombre.setName("NOMBRE"); // NOI18N

        campoApellidos.setName("APELLIDOS"); // NOI18N

        dateFechaNacimiento.setName("FECHA DE NACIMIENTO"); // NOI18N

        campoTelefono.setName("TELÉFONO"); // NOI18N

        campoEmail.setName("EMAIL"); // NOI18N

        comboCodigoPostal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboCodigoPostal.setName("CÓDIGO POSTAL"); // NOI18N

        buttonGroupSexo.add(radioMujer);
        radioMujer.setText("Mujer");

        buttonGroupSexo.add(radioHombre);
        radioHombre.setText("HOMBRE");

        buttonGroupSexo.add(radioOtros);
        radioOtros.setText("OTROS");

        buttonGroupAlcohol.add(radioNulo);
        radioNulo.setText("NULO");

        buttonGroupAlcohol.add(radioOcasional);
        radioOcasional.setText("OCASIONAL");

        buttonGroupAlcohol.add(radioHabitual);
        radioHabitual.setText("HABITUAL");

        buttonGroupTabaquismo.add(radioNo);
        radioNo.setText("NO");

        buttonGroupTabaquismo.add(radioSi);
        radioSi.setText("SI");

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(48, 48, 48)
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelCamposLayout.createSequentialGroup()
                                    .addComponent(radioNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioSi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelCamposLayout.createSequentialGroup()
                                    .addComponent(radioOcasional, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioHabitual, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioNulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelCamposLayout.createSequentialGroup()
                                    .addComponent(radioMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelCamposLayout.createSequentialGroup()
                                    .addComponent(campoEmail)
                                    .addGap(60, 60, 60)))
                            .addComponent(comboCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCamposLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(134, 134, 134)
                            .addComponent(campoTelefono))
                        .addGroup(panelCamposLayout.createSequentialGroup()
                            .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(52, 52, 52)
                            .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(campoDni)
                                .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(radioMujer)
                    .addComponent(radioHombre)
                    .addComponent(radioOtros))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(radioNo)
                    .addComponent(radioSi))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radioOcasional)
                    .addComponent(radioHabitual)
                    .addComponent(radioNulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAreas.setBorder(javax.swing.BorderFactory.createTitledBorder("Salud"));
        panelAreas.setOpaque(false);
        panelAreas.setRequestFocusEnabled(false);

        jLabel13.setText("ANTECEDENTES FAMILIARES DESTACABLES");

        campoAntecedente.setColumns(20);
        campoAntecedente.setRows(5);
        campoAntecedente.setName("ANTECEDENTES FAMILIARES"); // NOI18N
        jScrollPane2.setViewportView(campoAntecedente);

        jLabel14.setText("PERSONAL (ALERGIAS, CIRUGÍAS, ENFERMEDADES, ETC.)");

        campoPersonalAlerg.setColumns(20);
        campoPersonalAlerg.setRows(5);
        campoPersonalAlerg.setName("DATOS PERSONALES"); // NOI18N
        jScrollPane3.setViewportView(campoPersonalAlerg);

        javax.swing.GroupLayout panelAreasLayout = new javax.swing.GroupLayout(panelAreas);
        panelAreas.setLayout(panelAreasLayout);
        panelAreasLayout.setHorizontalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelAreasLayout.setVerticalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N

        jLabel2.setText("NUEVO PACIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed

// Tiene que:
//Primero Validamos todos los campos para que no esten vacios.
// A parte de lo normal, hay que validar los radioBotons. 
// Fecha de nacimiento tiene que ser anterior a hoy
// Telefono debe ser 9 valores numéricos
// email debe tener formato email
// 
// Una vez validados, tenemos que coger y encriptar Dni, nombre y apellidos.
// 
//Crearemos entonces un Paciente con los siguientes valores conseguidos
// 
// Enviaremos con una consulta en conexion estos valores a la base de datos
//
//Registrado el paciente deberá anunciarse el resultado con mensaje específico y se cerrará la ventana: “Paciente registrado correctamente”.
// En caso de error en el registro se emitirá el mensaje correspondiente: “Error en el registro del 
//paciente. Inténtelo más tarde o póngase en contacto con el administrador del sistema”.
//
        boolean comprobaciones = true;

        if (!utilidades.Utilidades.compruebaButtonRadios(buttonGroupSexo)) {
            comprobaciones = false;
        }
        if (!utilidades.Utilidades.compruebaButtonRadios(buttonGroupAlcohol) && comprobaciones) {
            comprobaciones = false;
        }
        if (!utilidades.Utilidades.compruebaButtonRadios(buttonGroupTabaquismo) && comprobaciones) {
            comprobaciones = false;
        }
        if (!utilidades.Utilidades.compruebaCamposVacios(panelCampos) && comprobaciones) {
            comprobaciones = false;
        }
        if (!utilidades.Utilidades.compruebaCamposVacios(panelAreas) && comprobaciones) {
            comprobaciones = false;
        }
//        if (!utilidades.Utilidades.validarDNI(dniPaciente) && comprobaciones == true) {
//            comprobaciones = false;
//        }
        if (!utilidades.Utilidades.validarEmail(campoEmail.getText()) && comprobaciones) {
            comprobaciones = false;
        }
        if (!utilidades.Utilidades.compruebaNumeroTelefono(campoTelefono) && comprobaciones) {
            comprobaciones = false;
        }        
        if (!dateFechaNacimiento.getDate().before(hoy) && comprobaciones) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento debe ser congruente.");
            comprobaciones = false;

        }
        String sexo = "H";
        String tabaco = "";
        String alcohol = "Ocasional";
        if (radioMujer.isSelected()) {
            sexo = "M";
        } else if (radioHombre.isSelected()) {
            sexo = "H";

        } else if (radioOtros.isSelected()) {
            sexo = "OTROS";
        }

        if (radioSi.isSelected()) {
            tabaco = "SI";
        } else if (radioNo.isSelected()) {
            tabaco = "NO";
        }

        if (radioOcasional.isSelected()) {
            alcohol = "Ocasional";
        } else if (radioHabitual.isSelected()) {
            alcohol = "Habitual";

        } else if (radioNulo.isSelected()) {
            alcohol = "Nulo";
        }

        if (comprobaciones) {

            String dni = Encriptado.encriptar(dniPaciente);
            String nom = Encriptado.encriptar(campoNombre.getText());
            String ape = Encriptado.encriptar(campoApellidos.getText());
            java.util.Date fec = dateFechaNacimiento.getDate();
            int tel = Integer.parseInt(campoTelefono.getText());
            String ema = campoEmail.getText();
            int cp = Integer.parseInt((String) comboCodigoPostal.getSelectedItem());
            String sex = sexo;
            String tab = tabaco;
            String alc = alcohol;
            String antSal = campoAntecedente.getText();
            String datAle = campoPersonalAlerg.getText();
            java.util.Date fechoy = hoy;

            Paciente p = new Paciente(dni, nom, ape, fec, tel, ema, cp, sex, tab, alc, antSal, datAle, fechoy);
            Conexion.Conectar();

            if (bbdd.Conexion.registrarPaciente(p)) {
                JOptionPane.showMessageDialog(this, "Paciente registrado correctamente");
                Conexion.desconectar();
                utilidades.Utilidades.reseteaFormulario(panelAreas);
                utilidades.Utilidades.reseteaFormulario(panelCampos);

            } else {
                Conexion.desconectar();
                JOptionPane.showMessageDialog(this, "Error en el registro, intentelo de nuevo.");
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoPaciente dialog = new NuevoPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.ButtonGroup buttonGroupAlcohol;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.ButtonGroup buttonGroupTabaquismo;
    private javax.swing.JTextArea campoAntecedente;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextArea campoPersonalAlerg;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox<String> comboCodigoPostal;
    private com.toedter.calendar.JDateChooser dateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelAreas;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JRadioButton radioHabitual;
    private javax.swing.JRadioButton radioHombre;
    private javax.swing.JRadioButton radioMujer;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioNulo;
    private javax.swing.JRadioButton radioOcasional;
    private javax.swing.JRadioButton radioOtros;
    private javax.swing.JRadioButton radioSi;
    // End of variables declaration//GEN-END:variables
}
